Feature/ekf localizaton
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #15
Opened 2022-12-27 06:38 UTC by bvbnatsu

## 概要

- `robot_pose_ekf`を`ekf_localization`に変更

### なぜこのタスクを行うのか

- `ekf_localization`を追加

### やったこと

- `~/catkin_ws/src`にパッケージ`robot_localization`を追加
- `igvc2023`の`package.xml`の`exec_depend`の`robot_pose_ekf`を`ekf_localization`に変更
- `igvc2023`の`start_sim.launch`と`sensor.launch`の`robot_pose_ekf`を`ekf_localization`に変更

### できるようになること

- `start_sim.launch`で`ekf_localization`を利用

### できなくなること

- 

### その他

- `start_sim.launch`を実行すると以下のようなエラーが出てしまいます。
**ubuntu@d68d467ecc85:~/catkin_ws/src$ roslaunch igvc2023/ start_sim.launch
RLException: [start_sim.launch] is neither a launch file in package [igvc2023/] nor is [igvc2023/] a launch file name
The traceback for the exception was written to the log file**

2022-12-28 06:11 UTC, Alpaca-zip commented
こちらはレビュー待ちですか？レビュー待ちの場合には、Reviewersを指定してください。

2022-12-28 13:39 UTC, bvbnatsu commented
遅れて申し訳ありません。
レビューよろしくお願い致します。

2022-12-28 14:07 UTC, koki0624 reviewed
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/issues/11#issuecomment-1362993555
エラーの内容はこれと同じかな？

2022-12-28 14:12 UTC, Alpaca-zip requested changes
- start_sim.launchは @bvbnatsu が編集を始めた時点から変更がなされているため、競合が発生しています。`git pull origin main`で一度、ローカルリポジトリをリモートリポジトリの最新の内容でマージしてください。
- start_sim.launchを実行時にエラーが出るとのことだけど、`roslaunch igvc2023/ start_sim.launch`ではなく、`roslaunch igvc2023 start_sim.launch`ではないでしょうか。

2022-12-28 14:12 UTC, Alpaca-zip commented on tsukuba2022/launch/start_sim.launch
> +    <node name="combine_dr_measurements" pkg="ekf_localization" type="ekf_localization" if="$(arg use_ekf)">
ekf_localizationは、robot_pose_ekfとはパッケージが異なる全くの別物なので、名前を変えるだけのような単純なものではありません。下は、適当にインターネットで引っ張ってきたものです。もちろん、このまま使うことはできないですが、探すと色々出てくるので試してみてください
```
<node pkg="robot_localization" type="ekf_localization_node" name="ekf_se" clear_params="true" output="screen">
  <rosparam command="load" file="$(find nav_lecture)/config/ekf_localization/mode2.yaml" />
  <param name="tf_prefix" value="dtw_robot1"/>
  <remap from="/odometry/filtered" to="/dtw_robot1/fusion/odom" />
  <remap from="odom0" to="diff_drive_controller/odom" />
  <remap from="odom1" to="tracking/choppy" />
</node>
```

2022-12-28 15:47 UTC, bvbnatsu commented
@koki0624 同じでした。
#11 確認します！

2022-12-28 15:49 UTC, bvbnatsu commented
@Alpaca-zip レビューいただきありがとうございます。
修正後、再度プルリクエストさせていただきます。

2023-01-14 02:54 UTC, kengohozumi commented
変更しました　確認よろしくお願いします。

2023-01-14 14:34 UTC, Alpaca-zip requested changes
しっかり動作しました。結構よくなってきたと思います。
少し追加で、直してほしいところがあるのでそちらだけ対応お願いしたいです。

- 以下、実機用のlaunchファイルにrobot _pose_ekfがまだ残っているので、こちらをrobot_localizationに変更してください。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/2e67739dad866e0c1e923d442bd768fdc4e718a3/igvc2023/launch/sensors.launch#L81-L92

- move_baseがオドメトリトピックを購読してますが、トピック名が合ってないので変更お願いします。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/2e67739dad866e0c1e923d442bd768fdc4e718a3/igvc2023/launch/waypoint_navigation.launch#L7
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/2e67739dad866e0c1e923d442bd768fdc4e718a3/igvc2023/launch/waypoint_navigation_multi.launch#L8

2023-01-14 14:34 UTC, Alpaca-zip commented on igvc2023/launch/start_sim.launch
> +    <node pkg="robot_localization" type="ekf_localization_node" name="ekf_se" clear_params="true" output="screen">
`name="ekf_se"`とありますが`se`がよくわからないので、もう少しわかりやすい名前に変えてもらえますか

2023-01-14 14:34 UTC, Alpaca-zip commented on igvc2023/launch/start_sim.launch
> +        <rosparam command="load" file="$(find igvc2023)/config/model1.yaml" />
`model1.yaml`も、もう少しわかりやすい名前に変えてもらえると助かります。

2023-01-14 14:34 UTC, Alpaca-zip commented on igvc2023/launch/start_sim.launch
> +        <remap from="/odometry/filtered" to="/odometry/filtered" />
`<arg name="odom" default="/odometry/filtered"/>`を追加して、`<remap from="/odometry/filtered" to="$(arg odom)" />`とするか、この行は無くてもいいと思います。

2023-01-15 03:32 UTC, kengohozumi commented
また　編集し直しました
確認お願いします。

2023-01-15 03:34 UTC, kengohozumi commented
今日は日曜日ですので確認は明日以降でも大丈夫です

2023-01-15 04:54 UTC, Alpaca-zip approved these changes
動作確認おっけーです！
commitメッセージを`featurerobotlocalization`としてもらってるけど、どういう編集したかがよくわからないので、今後は[ここ](https://github.com/KBKN-Autonomous-Robotics-Lab)のcommitメッセージの例で記述しているようにもう少し具体的に書いてくれると助かります。

こちらのPRはmainにマージしちゃいますー。お疲れ様でした！

2023-01-15 04:54 UTC, merged