fix/startsim
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #24
Opened 2023-01-13 09:49 UTC by kengohozumi

## 概要
シュミレーションのロボットのスタート位置の変更しました。

使い慣れてなくて迷惑おかけしました　すみません

2023-01-13 23:18 UTC, Alpaca-zip requested changes
以下の内容も対応お願いしてもいいですか？

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/pull/17#pullrequestreview-1245420320
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/pull/14#discussion_r1057201811

2023-01-14 01:35 UTC, kengohozumi commented
catkin buildなんですが

Errors     << velodyne_driver:cmake /home/ubuntu/catkin_ws/logs/velodyne_driver/build.cmake.000.log
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/boost_thread-1.71.0/boost_thread-config.cmake:107 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:24 (find_package)
のエラーが出てしまいました。

2023-01-14 05:42 UTC, koki0624 commented
> catkin buildなんですが
> 
> Errors << velodyne_driver:cmake /home/ubuntu/catkin_ws/logs/velodyne_driver/build.cmake.000.log CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message): Could NOT find Threads (missing: Threads_FOUND) Call Stack (most recent call first): /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE) /usr/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS) /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package) /usr/lib/x86_64-linux-gnu/cmake/boost_thread-1.71.0/boost_thread-config.cmake:107 (find_dependency) /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package) /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component) /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package) CMakeLists.txt:24 (find_package) のエラーが出てしまいました。

メモリ不足によるエラーな気がします。一旦
`cm -j2`
でビルドしてみてください。だめなら一度コンテナを止めて、不要なコンテナ、イメージ、ファイル等々の削除と、サーバの再起動をしてからもう一度試してみてください。再起動は
`sudo reboot`
でできます。

2023-01-14 05:44 UTC, kengohozumi commented
わかりました　ありがとうございます

2023-01-17 06:24 UTC, Alpaca-zip requested changes
機体の名前を、別の名前に変えてもらっていいですか？
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/e1883a97aa7827f4110746547bff3667de046087/igvc2023/launch/start_sim.launch#L6

2023-01-18 10:03 UTC, koki0624 commented
@shunsugar 
これはレビュー待ち？

2023-01-18 10:14 UTC, shunsugar commented
@koki0624 
頼まれて機体の名前変えただけなので大丈夫です！

2023-01-19 03:16 UTC, kengohozumi commented
ロボットの位置とマップの位置を変更しました。
start_simを立ち上げるのに

sudo catkin clean
sudo chown -R $ubuntu:$ubuntu .
catkin build	
source ~/.bashrc

sudo apt update
sudo apt upgrade
sudo apt install ros-noetic-robot-localization
をしないと毎回実行できないのですがこれは仕方ないのでしょうか？

2023-01-19 03:18 UTC, kengohozumi commented
終わったら
白線認識のブランチと
GPSのブランチを増やしたいです

2023-01-19 04:10 UTC, koki0624 commented
> ロボットの位置とマップの位置を変更しました。 start_simを立ち上げるのに
> 
> sudo catkin clean sudo chown -R $ubuntu:$ubuntu . catkin build source ~/.bashrc
> 
> sudo apt update sudo apt upgrade sudo apt install ros-noetic-robot-localization をしないと毎回実行できないのですがこれは仕方ないのでしょうか？

ありがとう！これからレビューしますね。
実行の話だけど、ノードとかの変更を反映させたいときはcatkin buildが必要です。それ以外のとき（launchやworldなどの変更）は基本的に何もしなくても反映されるはずです。「実行できない」の意味をもう少し詳しく教えてください。

2023-01-19 04:12 UTC, kengohozumi commented
すいません　実行できないというのはエラーになってしまうってことです

2023-01-19 04:27 UTC, koki0624 commented
> すいません　実行できないというのはエラーになってしまうってことです

こちらからは状況が分からないので、エラーの内容も示してもらえますか？
問題に関して質問するときは
- 発生した問題やエラーの詳細（「実行できない」、「エラーが起きた」だけだと伝わらない）
- 解決するためにやってみたこと（すでに試したことがあるなら解決策も絞られる）
この辺を示してくれるとスムーズなので助かります。

2023-01-19 05:17 UTC, Alpaca-zip commented
@shunsugar @kengohozumi 
> 終わったら 白線認識のブランチと GPSのブランチを増やしたいです

こちらの件について、以前教えたみたいにそれぞれissuesを立てて、Project(todoリスト)と紐付けてもらえますか？

2023-01-28 14:00 UTC, Alpaca-zip approved these changes
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/5231a7f763041cbcd4e89e94513ace58a75a9c64/igvc2023/package.xml#L29
@koki0624 がpackage.xmlを修正してくれたので実行も問題なくできます。ロボットの位置も名前もおっけーです。

@kengohozumi @bvbnatsu 
こちらはこれ以上編集することが無いようであればマージしてしまいますがよろしいですか？

2023-01-28 23:45 UTC, kengohozumi commented
はい　大丈夫です
ありがとうございます

2023-01-29 05:13 UTC, Alpaca-zip commented
@kengohozumi 
approveした後にすみません。
`igvc2023/urdf/orange2022.xacro`でコンフリクト起こしているのでそこだけ解決してもらってもいいですか？

2023-01-29 08:55 UTC, koki0624 commented
@Alpaca-zip @kengohozumi 
俺がカメラ追加した影響かなと思うのでマージ解決しちゃいました。やってたらごめんね。

2023-01-29 18:15 UTC, merged