add GPS
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #30
Opened 2023-01-31 13:25 UTC by kengohozumi

## 概要

-シュミレーションでGPSを使えるようにする

### やったこと

-orange.xacroの編集  gps.urdf.xacroの追加

### できるようになること

- robot_localizationでGPSが使えるようになる

2023-01-31 13:26 UTC, kengohozumi commented
エラーなく使えて、topicも出力を確認しました。
確認お願いします

robot_localizationにGPSを使えるようにするのはこのブランチで行ってもいいですか？

2023-01-31 14:28 UTC, koki0624 requested changes
シミュレーションを起動しましたが、gpsのトピックはpublishされていないようです。
推測ですが、何か追加でライブラリをインストールしたのではないでしょうか？
もしそうであれば、依存するライブラリがインストールできるようにpackage.xmlを編集していただけると助かります。

その他、気になる箇所をFiles changedの方にコメントしたので確認をお願いします。

2023-01-31 14:28 UTC, koki0624 commented on igvc2023/urdf/orange.xacro
> +  <!-- Import fisheye camera model -->
細かいですが、こういったコメントも気にしていただけるとありがたいです。

2023-01-31 14:30 UTC, koki0624 commented on igvc2023/urdf/sensors/gps.urdf.xacro
> +          <gaussianNoise>0.0 0.0 0.0</gaussianNoise>
実機に近づけるならノイズはあった方が良いと思うのですが、0でも大丈夫なのでしょうか？

2023-01-31 17:05 UTC, Alpaca-zip commented on igvc2023/urdf/sensors/gps.urdf.xacro
> +          <gaussianNoise>0.0 0.0 0.0</gaussianNoise>
こちらの件ですがgazeboのGPSはチート並の自己位置精度があるのでノイズは大きめに入れた方がいいかもしれません。

ノイズが大きい時と小さい時で比較してみてもらってもいいですか？

2023-02-02 13:33 UTC, kengohozumi commented
書き換えました
確認お願いします
ノイズに関してはこれから調整します

2023-02-02 19:29 UTC, koki0624 submitted a review, later dismissed
依存関係の解決と、gpsのトピックがpublishされていることが確認できたのでオッケーです！
マージはしないので、引き続きよろしくお願いします。

それと、ノイズの件に加えて、データのレートも実機とシミュレーションで差が出る要因になるので、気に留めておいてもらえると良いかと思います。

2023-02-03 03:59 UTC, Alpaca-zip approved these changes

2023-02-06 02:56 UTC, kengohozumi commented
シュミレーションでのnavsat_transform_nodeを使えるようにしました
確認お願いします
robot_localizationでGPSを使う上でのパラメータ調整は後ほどやります。
それが終わったら実機で使えるように書き換えます
実機で使う上でtty/ACMの追加が必要なのですがどうしたらいいでしょうか？
<node pkg="nmea_navsat_driver" type="nmea_serial_driver" name="navsat" respawn="true">
  <param name="port" value="/dev/ttyACM0"/>←
  <param name="baud" value="19200"/>
</node>
が必要です

2023-02-06 02:58 UTC, kengohozumi commented
シュミレーションでのnavsat_transform_nodeを使えるようにしました 確認お願いします 
robot_localizationでGPSを使う上でのパラメータ調整は後ほどやります。 
それが終わったら実機で使えるように書き換えます
 実機で使う上でtty/ACMの追加が必要なのですがどうしたらいいでしょうか？

2023-02-06 10:53 UTC, koki0624 commented
> シュミレーションでのnavsat_transform_nodeを使えるようにしました 確認お願いします 
とりあえず、エラーなく動くことは確認しました。

> 実機で使う上でtty/ACMの追加が必要なのですがどうしたらいいでしょうか？
つくばチャレンジのときに松本君に教えたような教えてないような気がするので、いったん聞いてみてください。
分からなければissueとかに投稿してもらえると助かります。

2023-02-06 11:01 UTC, koki0624 commented
@kengohozumi 
ロボットの初期方位（yaw）が3.14になっていたことで、robot_localicationのデータがおかしなことになっていたので、0にしてプッシュしました。

2023-02-06 11:06 UTC, Alpaca-zip commented
@kengohozumi 
うるさい様ですみません。reviewerに確認して貰いたい時は以前教えたように、レビューのRe-requestをしてください。よろしくお願いします。

2023-02-06 11:10 UTC, Alpaca-zip commented
> @kengohozumi
> ロボットの初期方位（yaw）が3.14になっていたことで、robot_localicationのデータがおかしなことになっていたので、0にしてプッシュしました。

@koki0624 こちらの件気づきませんでした。直してくれてありがとう！

2023-02-07 07:57 UTC, kengohozumi commented
2個目のfixはgit pullする前に変更してしまったため余分にcommitが増えてしまいました。
作り直したほうがいいですか？

2023-02-07 07:58 UTC, kengohozumi commented
2個目のfixはgit pullする前に変更してしまったため余分にcommitが増えてしまいました、、。

2023-02-07 15:08 UTC, koki0624 commented
> 2個目のfixはgit pullする前に変更してしまったため余分にcommitが増えてしまいました、、。

レビュー待ちならRe-requestしてねー

2023-02-08 03:23 UTC, Alpaca-zip requested changes
しっかりと動作確認していない状態でのレビューですみません。
GPSのgaussianNoiseの件はどうなりましたか？

2023-02-08 03:23 UTC, Alpaca-zip commented on igvc2023/launch/sensors.launch
> +        <param name="port" value="/dev/ttyACM0"/>
こちらimuやhokuyoでやっているのと同じようにargでdefaultを設定してもらっていいですか？

2023-02-08 03:42 UTC, Alpaca-zip commented
@kengohozumi 追加ですみません。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/450b33ac6da33dba2fd8436facff829586e93060/igvc2023/launch/sensors.launch#L92
こちら、`/odometry/filtered `をpublishしているのはnavsat_transform_nodeではなくekf_localization_nodeではないですか？

2023-02-09 13:42 UTC, kengohozumi commented
http://docs.ros.org/en/melodic/api/robot_localization/html/navsat_transform_node.html
を見ると/fixと/imuと/odometry/filteredの記述ですよね？
![image](https://user-images.githubusercontent.com/83738796/217828807-13819a85-b405-4db2-8051-d0e0601af0f1.png)

2023-02-09 13:46 UTC, kengohozumi commented
GPSのrateは1秒に一回(値10)で大丈夫です。
noiseに関しては他のgps.xacroを参考にして一旦値をそれぞれ0.05にしました。

2023-02-09 16:13 UTC, koki0624 reviewed
大分ごちゃついてきてるので、私からは以下の3つだけ指摘しておきます。

> GPSのrateは1秒に一回(値10)で大丈夫です。 noiseに関しては他のgps.xacroを参考にして一旦値をそれぞれ0.05にしました。

updateRateはHzだから、値10だと1秒に10回だよ。

---

> こちら、/odometry/filtered をpublishしているのはnavsat_transformではなくekf_localization_nodeではないですか？

<img width="343" alt="スクリーンショット_20230210_003500" src="https://user-images.githubusercontent.com/88423990/217863804-d59a18dd-004c-466e-b5f9-1a30feaa28f6.png">

pub-subの関係はこうみたいです。それと、remapのfromとtoが同じトピック名ならremapする必要はないかと思います。（やって問題もないので意図があるならそれもいいと思います。）

---

直進させたときの odometry/filterd と odometry/gps の出力をrvizで表示してみると  
<img width="372" alt="スクリーンショット_20230210_004330" src="https://user-images.githubusercontent.com/88423990/217865968-6eea26b2-d6be-4752-a597-52927bc71a27.png">
赤: odometry/gps　青: odometry/filtered  

こんな感じでした。gpsの方の値は軸の向きが違いそうだし、そのデータをekfが使っているのなら filtered の方は逆に正確すぎてちょっと気になります。  

このブランチはすでにいろいろ作業してしまっているので、簡単に解決できる部分だけ解決してマージしてから、別のブランチでパラメータの調整や問題解決をした方がいいかもしれません。 後は @Alpaca-zip に任せます。

2023-02-10 02:24 UTC, kengohozumi commented
確認ありがとうございます
アドバイスの元、rateは1に変えて1秒に一回にしました。
http://wiki.ros.org/hector_gazebo_pluginsにgps.xacroのパラメータ情報が書いてあってミリ秒なんですけど

remapの odometry/filterdは消去しました

すみません　gpsの方の値は軸の向きが違うというのはnoiseの調節が間違っていますか？？

2023-02-10 02:25 UTC, kengohozumi commented
確認ありがとうございます
アドバイスの元、rateは1に変えて1秒に一回にしました。
http://wiki.ros.org/hector_gazebo_plugins
にgps.xacroのパラメータ情報が書いてあってミリ秒なんですけど]

remapの odometry/filterdは消去しました

すみません　gpsの方の値は軸の向きが違うというのはnoiseの調節が間違っていますか？？

2023-02-10 13:01 UTC, koki0624 commented
> 確認ありがとうございます アドバイスの元、rateは1に変えて1秒に一回にしました。 http://wiki.ros.org/hector_gazebo_plugins にgps.xacroのパラメータ情報が書いてあってミリ秒なんですけど

`rostopic hz トピック名` でデータのレートを確認できます。/fix のレートは1になっているので問題ないかと。

<br>
 
> すみません　gpsの方の値は軸の向きが違うというのはnoiseの調節が間違っていますか？？

noiseの問題ではないと思います。推測ですが、nav_sat_transformが前提としているシミュレーション上の緯度経度の方向（方角）と、x軸y軸の方向にずれがあるのではないでしょうか。
軸の向きが違うのに odometry/filtered は正確なのも気になります。

2023-02-10 13:35 UTC, Alpaca-zip requested changes
幾つか確認したいことがあります。
___
1. WSLの問題なのかRviz上でrobotのモデルがCollisionしか出てきません。Dockerの方で問題なければこちらの問題なので大丈夫です。

3. `gps_link`がロボットの中心軸からずれた位置にありますがこれは仕様ですか？

<img src="https://user-images.githubusercontent.com/84959376/218101429-60496aa8-1fa9-4cb0-b6d5-54b5b1ea42c2.png" width="400px">  

3. 以下のコードの部分は実機で動作確認済みでしょうか。

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/1e63befcea4dc62956b004432899f7b6bf26ff2b/igvc2023/launch/sensors.launch#L95-L98
___
> 確認ありがとうございます アドバイスの元、rateは1に変えて1秒に一回にしました。 http://wiki.ros.org/hector_gazebo_plugins にgps.xacroのパラメータ情報が書いてあってミリ秒なんですけど]

トピックの周期を確認してみましたが`updateRate`が1のときに1Hzだったのでミリ秒の記述が間違いなように感じます。

<img src="https://user-images.githubusercontent.com/84959376/218103823-0791b606-9ae0-4c22-997a-711027a96a0b.png" width="400px">  

> このブランチはすでにいろいろ作業してしまっているので、簡単に解決できる部分だけ解決してマージしてから、別のブランチでパラメータの調整や問題解決をした方がいいかもしれません。 後は @Alpaca-zip に任せます。

そうだねー。パラメータ調整に関しては別でissue立てたほうがよさそう。
とりあえず`nmea_navsat_driver`が実機で動作出来ているようであれば、必要な修正だけ直してもらって、このPRはマージします。

2023-02-10 13:35 UTC, Alpaca-zip commented on igvc2023/package.xml
> +    <exec_depend>nmea_navsat_driver</exec_depend>
インデントがずれているので修正お願いします。

2023-02-10 13:35 UTC, Alpaca-zip commented on igvc2023/launch/start.launch
> +    <arg name="gps_dev"          default="/dev/ttyACM0"/>
`/dev/sensors/gps`のような形で他と名前を合わせてもらった方が良いと思います。

2023-02-10 15:40 UTC, Alpaca-zip commented
@kengohozumi @koki0624 
新しくissueを立てておきました。robot_localizationのパラメータに関する議論はこちらのissueでお願いします。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/issues/34#issue-1579892306

2023-02-11 00:34 UTC, kengohozumi commented on igvc2023/launch/start.launch
> +    <arg name="gps_dev"          default="/dev/ttyACM0"/>
devに関してなんですけど2つ同じ受信機を使おうと思っててttyACMの番号の区別ができなかったんですよね、、
なのでttyACM0、ttyACM1で前やっていました、

2023-02-11 00:41 UTC, kengohozumi commented
シュミレーションの受信機を少しずらしたのは
実機では2つ受信機を設置しようと思っていて自己位置推定を行う受信機はロボットの後方右側に設置をするので少しずらしていました、、
rvizの矢印を見た感じ軸中心に設置しないと自己位置推定に影響しそうですよね、、、

2023-02-11 02:30 UTC, Alpaca-zip commented on igvc2023/launch/start.launch
> +    <arg name="gps_dev"          default="/dev/ttyACM0"/>
なるほど。そしたらとりあえずは、`/dev/ttyACM0`で大丈夫です。受信機はアメリカでも使える代物ですか？

2023-02-11 02:31 UTC, Alpaca-zip commented
> シュミレーションの受信機を少しずらしたのは 実機では2つ受信機を設置しようと思っていて自己位置推定を行う受信機はロボットの後方右側に設置をするので少しずらしていました、、 rvizの矢印を見た感じ軸中心に設置しないと自己位置推定に影響しそうですよね、、、

そうだね。中心に直してもらっていいですか。

2023-02-14 06:31 UTC, Alpaca-zip approved these changes
@koki0624 @kengohozumi 
とりあえず私の気になる点は解消されていますが、こちらはマージしてしまっていいですか？

2023-02-14 07:00 UTC, koki0624 commented
> @koki0624 @kengohozumi とりあえず私の気になる点は解消されていますが、こちらはマージしてしまっていいですか？

いいと思うよー

2023-02-15 06:04 UTC, Alpaca-zip approved these changes

2023-02-15 06:04 UTC, merged