feature dev
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #50
Opened 2023-04-06 05:00 UTC by kengohozumi

## 概要

-ナビゲーションにカメラ、LED、gpsを使えるようにdevを追記しました。

2023-04-06 07:33 UTC, Alpaca-zip requested changes

2023-04-06 07:33 UTC, Alpaca-zip commented on igvc2023/launch/start.launch
> +    <!-- Start sensors (hokuyo, velodyne, imu, camera, LED) -->
```suggestion
    <!-- Start sensors (hokuyo, velodyne, imu, camera, LED, gps) -->
```
コメントアウト文を修正するようであれば上記のようにgpsも入れていただきたいです。

2023-04-12 01:53 UTC, kengohozumi commented
コメントアウトの部分を直しました

2023-04-12 02:29 UTC, Alpaca-zip approved these changes
問題ないと思います。

2023-04-12 02:29 UTC, merged