feature/navbool
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #51
Opened 2023-04-06 07:01 UTC by kengohozumi

## 概要

-ナビゲーションを開始したときにnavboolのトピックメッセージを送れるようにしました。

2023-04-06 08:10 UTC, Alpaca-zip requested changes
そもそもこの`waypoint_nav.cpp`はwaypointファイルを読み込んでナビゲーションを行うものですが、IGVCでは環境地図を作ることが難しいため、事前にwaypointファイルを用意するのも難しいように思います。
事前に敷かれたwaypointに追従するではなく、waypointを逐次的に生成して追従する方が望ましいです。

2023-04-06 08:10 UTC, Alpaca-zip commented on waypoint_navigation/waypoint_nav/src/waypoint_nav.cpp
> +            ROS_INFO("navBool:true published!");
この処理だと、while文の先頭で`navBool.data = true;`にしてトピックをpublishしているので、ナビゲーションが終わったとしても`/navBool`は`true`をpublishし続けると思います。
”ナビゲーション開始時”と”最後のウェイポイントにたどり着いた後の再開時”のみ`navigation_start_pub.publish(navBool);`を実行するなどの改善をお願いします。

2023-04-06 08:12 UTC, Alpaca-zip commented
私たちが作っていたnavigationのソースコードがgitbucketにあるのでそちらを引っ張ってきた方が良いと思います。

2023-04-06 11:14 UTC, koki0624 commented
@kengohozumi @bvbnatsu 
gitbucket の igvc2022/src に、当時実行していたlaunchファイルについて軽く説明するreadme.txtを追加しました。
そこから使っていたプログラムを追ってもらえればと思います。分からないことはまた聞いてください。

@Alpaca-zip 
GPS関連で使っていたプログラムが分からなかったので、時間あったら追記してもらえると助かります。

2023-04-06 14:01 UTC, Alpaca-zip commented
> GPS関連で使っていたプログラムが分からなかったので、時間あったら追記してもらえると助かります。

@kengohozumi 
GPS関連のこともreadme.txtに追記しておいたので確認してみてください。

2023-04-12 05:22 UTC, kengohozumi commented
すみません、waypointを逐次的に生成して追従するというのはyamlファイルを読み込みの仕方を変更するという意味でしょうか、、、？

2023-04-12 06:20 UTC, koki0624 commented
> すみません、waypointを逐次的に生成して追従するというのはyamlファイルを読み込みの仕方を変更するという意味でしょうか、、、？

事前に知っているGPSのウェイポイント座標はyamlファイルに記述しておいて、その付近に来たらそれを使います。
それまでは、障害物を回避しながら白線を追従するわけで、事前に座標でどこを通ればいいかはわかりません。
なので、LiDARとカメラで得た情報から数メートル先にゴールを設定する、という処理を逐次的に行うという方法をとっていました。（ゴールの設定の部分はmove_baseの機能をつかっています。）
[ownCloud - arl](https://www.ikko-lab.k.hosei.ac.jp/owncloud/index.php/apps/files/?dir=/2022/IGVC/%E3%83%87%E3%82%B6%E3%83%AC%E3%83%9D/%E7%99%BA%E8%A1%A8%E7%94%A8&fileid=257835)
上記の場所に「IGVC経路計画システム.pptx」というファイルがあるので、見てみてください。

2023-04-16 07:44 UTC, Alpaca-zip commented
@kengohozumi 
こちらのPRですが、必要ないと判断した場合にはCloseしてください。

2023-04-16 07:54 UTC, closed without merging