feature startlaunch
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #55
Opened 2023-04-14 10:17 UTC by kengohozumi

## 概要

igvc2023のstart.launchにigvc2022のstart.launchで不足している行を追加しました。

### その他

-ground_segmentationのインストールができません、、

2023-04-15 01:42 UTC, Alpaca-zip requested changes
> igvc2023のstart.launchにigvc2022のstart.launchで不足している行を追加しました。
- 概要には上記の記述がありますが、変更履歴を見るとstart.launchには何も変更がありません。これはcommit先を間違えたものですか？それとも概要が間違ってますか？

- 下記のパスの`params`は`config`の間違いではありませんか？
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/feature/start.launch/igvc2023/launch/segmentation.launch#L6

2023-04-15 01:44 UTC, Alpaca-zip commented on igvc2023/launch/segmentation.launch
> +    </node> -->
ここの変更、必要ですか？

2023-04-15 01:50 UTC, Alpaca-zip commented
> -ground_segmentationのインストールができません、、

上記だけだとアドバイスがしにくいのでもう少し詳細に、現状を説明してくれると嬉しいです。インストールが出来ないというのはどういう意味ですか？

2023-04-15 14:07 UTC, kengohozumi commented on igvc2023/launch/segmentation.launch
> +    </node> -->
すみません、start_sim.launchを実行する時にground_segmentationのエラーが出てしまいコメントアウトをずらしてしまいました。
ここのground_segmentationを使うためのpackage.xmlの追加する記述はigvc2022のpackage.xmlのどの行ですか、、？

2023-04-15 14:09 UTC, kengohozumi commented
すみません　start.launch関連のsensors.launch、segmentation.launchでの不足していた行を追加していました。

2023-04-16 06:52 UTC, Alpaca-zip commented on igvc2023/launch/segmentation.launch
> +    </node> -->
> すみません、start_sim.launchを実行する時にground_segmentationのエラーが出てしまいコメントアウトをずらしてしまいました。

- `git commit`する前に`git diff`コマンドで、無駄な変更がないかを確認してみるとよいと思います。インデント修正やコードの可読性向上を目的とする意図的な変更の場合には、別commitに分けてpushしていただけるとcommit logがより見やすくなると思います。

> ここのground_segmentationを使うためのpackage.xmlの追加する記述はigvc2022のpackage.xmlのどの行ですか、、？

どういう実行手順で依存関係を解決しようとして、結果としてどのようなエラーが出たのかの説明がないため、以下は憶測です。

1. package.xmlの以下の行に`<exec_depend>linefit_ground_segmentation_ros</exec_depend> `を追記。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/2d20e6d14c28d26b6807d83cfc7e3e5676a4a2d9/igvc2023/package.xml#L9-L32

2. `rosdep install`コマンドで依存関係を解決しようとしたが、rosdepが`linefit_ground_segmentation_ros`を見つけられずインストールがされなかった。

3. したがって、start_sim.launchの実行時にも`linefit_ground_segmentation_ros`を見つけられずエラーを出力してプロセスが終了した。

上記のような問題が発生したと仮定すると、私の知る限りでは、以下の二つの解決策が考えられます。

- 該当するリポジトリを`git clone`する。
該当リポジトリ：https://github.com/lorenwel/linefit_ground_segmentation

- `IGVC2023-src/`に`igvc2023_src.rosinstall`のようなファイルを作り、ファイルに以下を記述して[wstool](http://wiki.ros.org/wstool)で依存関係を解決する。
```
- git:
    local-name: linefit_ground_segmentation
    uri: https://github.com/lorenwel/linefit_ground_segmentation.git
    version: master
```

`git clone`もしくはwstoolいずれかを使うにせよ[Dockerfile](https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-docker/blob/main/Dockerfile)を書き直した方がいいと思います。

ROSの主要なパッケージはrosdepで依存関係を解決できますが、以下に登録されていないROSパッケージはrosdepでは解決できないと思います。
https://github.com/ros/rosdistro/tree/master/rosdep

2023-04-16 07:38 UTC, Alpaca-zip requested changes

2023-04-16 07:38 UTC, Alpaca-zip commented on igvc2023/config/segmentation_params.yaml
> +visualize: false           # visualize segmentation result - USE ONLY FOR DEBUGGING
> - 下記のパスの`params`は`config`に変更する必要があると思います。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/feature/start.launch/igvc2023/launch/segmentation.launch#L6

先日、上記のように伝えましたが、以下のパスに既に`segmentation_params.yaml`が存在しているので、この変更はrevertしてください。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/feature/start.launch/igvc2023/params/segmentation_params.yaml

2023-04-17 13:40 UTC, Alpaca-zip requested changes
- linefit_ground_segmentationがサブモジュール化されていて、git cloneしてもディレクトリが空の状態なので、以下の記事参考にしながら修正してください。
https://qiita.com/fuwakun/items/d2ea19bf43eda3df0094

- 以下の件、対応していただけてないと思います...。

> 先日、上記のように伝えましたが、以下のパスに既に`segmentation_params.yaml`が存在しているので、この変更はrevertしてください。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/feature/start.launch/igvc2023/params/segmentation_params.yaml

2023-04-19 09:21 UTC, kengohozumi commented
すいません　linefit_ground_segmentationの追加はできていますか？
start_sim.launchはエラーが起こらずに実行できたのですが、、

2023-04-19 12:20 UTC, kengohozumi commented
ground_segmentation.launchの14行目をobstacle_cloudに変更しました。

2023-04-19 13:14 UTC, merged