add no_map_navigation
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #57
Opened 2023-04-15 15:17 UTC by kengohozumi

## 概要

- igvc2022で行っていたno_map_navigation.launchと不足しているプログラムの追加を行いました。

### その他

-gps_waypoints_north.yamlとgps_waypoints_south.yamlはadd/waypointsaveのブランチで追加を行います。

2023-04-15 15:21 UTC, kengohozumi commented
すみません　gps_goal_setter.pyとlocal_goal_setter.pyには
gps_goal_setter1、gps_goal_setter2、
local_goal_setter1、local_goal_setter2、local_goal_setter3
とあるのですが何が違うのですか、、？

2023-04-16 07:30 UTC, Alpaca-zip requested changes
こちらは動作確認済みですか？
`no_map_navigation.launch`を見るに、明らかにファイルが足りていない箇所があります。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/d9d703547ec7687003b4d76a54acfff54befb0e3/igvc2023/launch/no_map_navigation.launch#L7-L8

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/d9d703547ec7687003b4d76a54acfff54befb0e3/igvc2023/launch/no_map_navigation.launch#L36

mainブランチは動作が保証されている安定なバージョンを置く場所です。なので、実機で動作確認するのは難しいにせよ、シミュレーション環境での動作確認などはしっかり行なってください。そうでないとブランチ保護やPRの意味がなくなってしまいます。

2023-04-16 09:32 UTC, koki0624 commented
> すみません　gps_goal_setter.pyとlocal_goal_setter.pyには gps_goal_setter1、gps_goal_setter2、 local_goal_setter1、local_goal_setter2、local_goal_setter3 とあるのですが何が違うのですか、、？

全く覚えてないので、一応プログラムを見て思い出した範囲で回答しておきます。
- どちらのプログラムも、\~2 以降でノードのリレー（白線追従とGPSナビそれぞれを担うノードの切り替え）の方法を変えたようです。なので基本的には\~2以降で考えてもらえればと思います。
- local_goal_setterの2と3では、微妙にアルゴリズムを変えています。最終的には2の方を使っていたようなので、まずはこちらを見てもらえればいいかと思います。

2023-04-16 10:40 UTC, Alpaca-zip commented
> すみません　gps_goal_setter.pyとlocal_goal_setter.pyには gps_goal_setter1、gps_goal_setter2、 local_goal_setter1、local_goal_setter2、local_goal_setter3 とあるのですが何が違うのですか、、？

前提として、逐次的にウェイポイントを生成して追従する`local_goal_setter`、gpsのウェイポイントに追従するための`gps_goal_setter`、コース上のスロープを上って降りるまでの処理を実現する`ramp_detect`の3つのノードがあります。
※`ramp_detect`は本番では利用しませんでした。
___

**`local_goal_setter.py` -> `local_goal_setter2.py`**

主に以下を修正しています。

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/src/local_goal_setter2.py#L45-L53

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/src/local_goal_setter2.py#L262-L297

実際には`local_goal_setter`、`gps_goal_setter`、`ramp_detect`の3つのノードをどの順番で実行するかを考える必要があります。`local_goal_setter.py`では、ソースコード内で次に実行するノードを指定していますが、`local_goal_setter2.py`ではノードの実行順番をパラメータとして持たせることで自由度の向上を実現しています。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/launch/no_map_navigation.launch#L49-L51
___
**`gps_goal_setter.py` -> `gps_goal_setter2.py`**

主に以下を修正しています。

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/src/gps_goal_setter2.py#L66-L89

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/src/gps_goal_setter2.py#L184-L192

こちらの変更も、`local_goal_setter.py` -> `local_goal_setter2.py`と同様に、ノードの実行順番をパラメータとして持たせることで自由度の向上を実現しています。
___
**`gps_goal_setter2.py` -> `gps_goal_setter3.py`**

主に以下を修正しています。

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/src/local_goal_setter3.py#L110-L122

https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/bab565335859927c7468d798819c6f2cb1ecca72/igvc2022/src/local_goal_setter3.py#L134-L171

ロボットがウェイポイントに向かって移動する際に、ロボットの前方にあるスペースが十分にあることを確認し、ロボットが進行方向に進むことができる場合にのみ、ロボットの周囲にある障害物を表示するスクリプトが追加されています。
どういう経緯でこの変更がなされたのかはよく覚えていませんが、おそらくデバッグ用ではないかと思います。
___
その他、小さな変更はいくつかありますが、そちらはソースコードを参照してください。

@koki0624 
間違っている点や追加があれば教えてください。

2023-04-17 15:01 UTC, koki0624 commented on igvc2023/scripts/waypoints_nav_igvc2023.cpp
こちらのプログラムは使用予定ですか？

2023-04-19 02:33 UTC, kengohozumi commented
すみません　lanchでコメントアウトされてたので使うときがあるかもしれないと思い、一応入れた程度でした。
waypoint_nav_igvc2023.cpp は使用予定ないので消去しました。

2023-04-25 04:55 UTC, Alpaca-zip commented
一旦こちらは、マージしてしまいます。何か追加で問題が起きた場合にはissue出して対応してください。

2023-04-25 04:55 UTC, Alpaca-zip approved these changes

2023-04-25 04:55 UTC, merged