IGVC用のURDFファイルの作成
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #65
Opened 2023-04-28 08:04 UTC by bvbnatsu

## 概要

- IGVC2023の機体のCOLLADAファイル(`IGVG2023chassis.dae`)の追加と、IGVC用にURDFファイル(`orange.xacro`)の変更を行いました。

### なぜこのタスクを行うのか

- シミュレーション用の機体を変更するためj。

### やったこと

- `IGVG2023chassis.dae`の追加
- `orange.xacro`の変更

### できるようになること

- 新しい機体でのシミュレーション

### できなくなること

- 

### その他

-

2023-04-30 08:10 UTC, Alpaca-zip commented
@bvbnatsu 誰にレビューをしてもらいたいかを指定してくれると助かります。Reviwersが指定されていないと通知が飛んできません。

2023-04-30 08:19 UTC, Alpaca-zip commented on igvc2023/meshes/IGVCchassis.dae
> +    <geometry id="立方体_041-mesh" name="立方体.041">
COLLADAファイル内で日本語が使われているのが気になります。
コードに日本語が含まれていると、バグを生む原因となるので修正した方が良いと思いますが、修正は可能ですか？

2023-04-30 11:34 UTC, bvbnatsu commented on igvc2023/meshes/IGVCchassis.dae
> +    <geometry id="立方体_041-mesh" name="立方体.041">
すみません。以後気をつけます。
日本語を英語に修正しました。
確認のほど宜しくお願い致します。

2023-05-01 12:55 UTC, Alpaca-zip requested changes
<img src="https://user-images.githubusercontent.com/84959376/235453599-a52c2a58-f87c-40a3-8aef-8c9c8cdb31f8.png" width="400px">

- `base_link`のcollisionがシャーシのフレームよりも大分小さいですが、これは問題ありませんか？
- `gps_link`のvisualとcollisionの位置がずれているのは修正した方が良いと思います。

2023-05-10 10:53 UTC, bvbnatsu commented
修正いたしました。
確認よろしくお願いします。

2023-05-10 10:55 UTC, Alpaca-zip commented
> 修正いたしました。 確認よろしくお願いします。

確認してもらいたいときは、レビューのRe-requestをしていただけると助かります。
今回は私の方でやっておきます。

2023-05-10 11:23 UTC, merged