foot_print.yamlの変更
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #67
Opened 2023-05-10 11:15 UTC by bvbnatsu

## 概要

- `foot_print.yaml`の変更

### なぜこのタスクを行うのか

- `move_base`で使用する機体の大きさを変える必要があるため

### やったこと

- `foot_print.yaml`のパラメーターをIGVC2023用の機体の大きさに変更

### できるようになること

- 

### できなくなること

- 

### その他

-

2023-05-10 12:23 UTC, Alpaca-zip requested changes

2023-05-10 12:36 UTC, bvbnatsu commented
承知致しました。
変更しました。

2023-05-10 16:34 UTC, Alpaca-zip reviewed
ロボットの幅と比べてfootprintの幅は大分余裕を持った値になっていますが、前後の長さに関してはぴったりになっています。ぴったりにするのか、余裕を持たせるのかはどちらかに統一した方が良いのではないでしょうか。

2023-05-11 02:35 UTC, bvbnatsu commented
承知しました。横幅もぴったりにしました。
URDFファイルを作る際、測定のミスで、URDFのタイヤの幅と、`zlac6080d_ros/params/motor_driver_params.yaml`の`wheel_base_width`の値がだいぶ違っていました。後でURDFの方を修正するので、`wheel_base_width`の方に合わせておきます。
あと、mainブランチの`wheel_base_width`が`0.608`なっていますが`0.58`が正しいです。こちらも後で修正します。

2023-05-11 04:41 UTC, Alpaca-zip commented
> 承知しました。横幅もぴったりにしました。
URDFファイルを作る際、測定のミスで、URDFのタイヤの幅と、zlac6080d_ros/params/motor_driver_params.yamlのwheel_base_widthの値がだいぶ違っていました。後でURDFの方を修正するので、wheel_base_widthの方に合わせておきます。
あと、mainブランチのwheel_base_widthが0.608なっていますが0.58が正しいです。こちらも後で修正します。

一応確認ですが、`wheel_base_width`はタイヤとタイヤの中心間距離なので、実際の車体幅は、`wheel_base_width+タイヤ幅`だと思います。

2023-05-15 03:07 UTC, bvbnatsu commented
前方の座標を`wheel_base_width+タイヤ幅`に合わせ、後方の座標をタイヤの中心間距離に変更しました。

2023-05-15 14:02 UTC, Alpaca-zip commented on igvc2023/params/foot_print.yaml
> +footprint: [ [0.2, 0.35], [0.2, -0.35], [-1.4, -0.29], [-1.4, 0.29] ]
0.35はどのように計算しましたか？
以下の計算式だと思いますが違いますか？

(0.58+0.047)/2=0.3135≃0.32
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/f9646c20ad7619abf9f7e0d4c1797bc57a0f209b/igvc2023/urdf/orange.xacro#L152
```suggestion
footprint: [ [0.2, 0.32], [0.2, -0.32], [-1.4, -0.32], [-1.4, 0.32] ]
```
0.35はどのように計算しましたか？

2023-05-15 17:10 UTC, bvbnatsu commented
すいません。。
タイヤの幅を推測でやってました。
0.32でお願いします。

2023-05-15 17:17 UTC, Alpaca-zip approved these changes

2023-05-15 17:17 UTC, merged