Change tsukuba2022 to igvc2023
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #7
Opened 2022-12-18 10:02 UTC by Yutarop

## 概要

- タスク1

### なぜこのタスクを行うのか

- githubを使った開発に慣れるため

### やったこと

- tskuba2022 のディレクトリの名前をigvc2023に変更

### できるようになること

- 

### できなくなること

- 

### その他

-mvコマンドでtskuba2022 のディレクトリをigvc2023に変更し、git add コマンドでigvc2023配下の全てのファイルを追加しました。ご確認のほどよろしくお願いいたします。

2022-12-18 12:05 UTC, Alpaca-zip requested changes
igvc2023という新しいディレクトリを作ったと思うけど、ROSはパッケージをディレクトリの名前で管理していないので、tsukuba2022が２つあると勘違いしてcatkin_wsのビルドが通りません。他にも修正箇所がたくさんあるので確認してみてください。
![スクリーンショット (364)](https://user-images.githubusercontent.com/84959376/208295566-a02b3c55-610f-4059-88ba-f5eef177122e.png)
#4 ここにも書いてあると思うけど、`igvc2023`の`start_sim.launch`が`igvc2023/world/course_v2.world`をデフォルトでspawnするように変更もしてほしいです。
大変だと思うけど、よくデバッグしたうえで再度プルリクエスト提出してもらえると助かります。

2022-12-18 12:56 UTC, Yutarop commented
承知しました。ご確認ありがとうございます。

2022-12-20 06:21 UTC, Alpaca-zip requested changes
@bvbnatsu 再度レビューのリクエスト貰ったけど何か変わったー？
もし修正したらcommitとpushをしてから再度リクエストお願いします。

2022-12-21 04:37 UTC, bvbnatsu commented
@Alpaca-zip すいません。間違えて送ってしまいました。

2022-12-21 08:25 UTC, closed without merging