orange.xacroの修正
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #70
Opened 2023-05-17 08:34 UTC by bvbnatsu

## 概要

- URDFファイルの機体の大きさが実寸値と違っていたため修正しました。

### なぜこのタスクを行うのか

- 

### やったこと

- 

### できるようになること

- 

### できなくなること

- 

### その他

-

2023-05-17 12:42 UTC, koki0624 requested changes
シミュレーションを起動し、rvizでRobotModelを確認したところ、以下の画像のようになりました。
![image](https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/assets/88423990/d0c99ad5-d80d-419d-8a81-e2a03fcf97d3)

また、ターミナルには以下のエラーが出ました。
![image](https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/assets/88423990/0f991bed-19e6-444f-a37c-fe59d5a45d89)

エラーメッセージから察するに、IGVCchassis.daeの18行目のidと、20行目のsourceが一致していないことが原因かと思われるので、修正をお願いします。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/08581710c683833f18bc89f1ade108a890753aff/igvc2023/meshes/IGVCchassis.dae#L18-L20

2023-05-17 12:52 UTC, koki0624 commented
no_map_navigation.launchを起動してrvizでfootprintを確認しました。
![image](https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/assets/88423990/5fad2fec-aa39-452a-b3d8-9b4b91de6980)

後輪の位置の問題であれば修正をお願いします。collisionも修正が必要かもしれません。

2023-05-17 17:07 UTC, bvbnatsu commented
@koki0624 
IGVCchassisの変更を行いました。

2023-05-17 17:12 UTC, bvbnatsu commented
foot_print.yamlの修正も行いました。

2023-05-20 09:52 UTC, koki0624 approved these changes
確認できました。オッケーです。

2023-05-20 09:52 UTC, merged