Fix/ramp detect
KBKN-Autonomous-Robotics-Lab/IGVC2023-src pull request #74
Opened 2023-06-03 06:51 UTC by koki0624

## 概要

- ramp_detect.pyの、ノード切り替え部分のプログラムを修正
- 一部のパラメータ、アルゴリズムを改善

### できるようになること

- no_map_navigation.launchのparam "node_array" を、...34... と設定すると実行されます。以下、大まかなプログラムの流れです。
1. "3" のときはlocal_goal_setterも同時に動いているため、坂の手前の白線を追従しながら一定距離以内に坂が検出されるまで待機
2. 検出されたらnode_indexを+1してnode_arrayの"4"の状態に切り替える（local_goal_setterはここで終了）
3. 切り替わる、と検出した坂の手前で坂に正対する向きにゴールを設定しながら近づく
4. 一定距離まで坂に近づき、かつ正対していることが確認できたら、下り終わるまではひたすら直進
5. 下り終わったことを確認したらnode_indexを+1して終了

### その他

- 変更する可能性があるパラメータの説明を書いておきます。変更する場合ファイル内33~38行目を書き換えてください。

- max_range [m] : この距離以内に坂が検出されれば、状態を"3"から"4"へ切り替える
- approach_range [m] : 検出した坂に近づくときの最大距離（厳密にはこの距離×2くらい以上は近づかない）
- climb_speed [m/s] : 坂を上るときの速度
- down_speed [m/s] : 坂を下るときのスピード
- run_hz : /hokuyo_scan のデータに対しrun_hz 回に1回処理を行う（坂を上り始めるまでの間のみ有効）

2023-06-03 06:57 UTC, Alpaca-zip commented
今日の夜中には内容確認しておきます。

2023-06-03 14:40 UTC, Alpaca-zip requested changes
@koki0624 
遅くなってすみません。動作確認はできていませんが気になった点はコメント残しておきました。
___
@kengohozumi @bvbnatsu 
時間が限られていると思うので、修正を待たずに各自必要であればこのブランチにコミットを追加しても構いません。

2023-06-03 14:40 UTC, Alpaca-zip commented on igvc2023/scripts/ramp_detect.py
> +		self.max_range = 5.0 #[m]
下記の計算は、`self.max_range`が初期化される前に行われているためエラーになりませんか？
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/efd6c7061fb3d203c053687b1ff67dc604cadb1d/igvc2023/scripts/ramp_detect.py#L31

2023-06-03 14:40 UTC, Alpaca-zip commented on igvc2023/scripts/ramp_detect.py
> +				end_ramp = self.downRamp(self.down_speed) # in this function, set node_flag to 1
誤解を生みそうなので、こちらのコメントは削除してしまった方が良いと思います。
```suggestion
				end_ramp = self.downRamp(self.down_speed)
```

2023-06-03 14:48 UTC, bvbnatsu approved these changes

2023-06-04 03:50 UTC, kengohozumi commented
北コースと南コースでウェイポイントを取りました

2023-06-15 07:13 UTC, closed without merging

2023-06-15 07:56 UTC, kengohozumi commented
rampは2DLidarを傾けて走行させてハード的な対策をしたので、detect rampのプログラムは使用しなかった。